add_newline = true

format = "$username[@](bold green)$hostname[:](bold green) $directory\n$character"

[username]
style_root = 'bold red'
style_user = 'bold green'
detect_env_vars = []
format = '[$user]($style)'
show_always = true
disabled = false
aliases = {}

[hostname]
ssh_only = false
ssh_symbol = 'ssh:'
trim_at = ''
detect_env_vars = []
format = '[$ssh_symbol$hostname]($style)'
style = 'bold green'
disabled = false
aliases = {}

[directory]
truncation_length = 0
truncate_to_repo = false
format = '[$path]($style)[$read_only]($read_only_style)'
style = 'bold cyan'
disabled = false
read_only = '!'
read_only_style = 'bold red'
truncation_symbol = ''
before_repo_root_style = 'bold cyan'
repo_root_style = 'bold yellow'
repo_root_format = '[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style)'
home_symbol = '~'
use_os_path_sep = true

[character]
format = '$symbol '
success_symbol = '[>](bold green)'
error_symbol = '[>](bold red)'
vimcmd_symbol = '[<](bold green)'
vimcmd_replace_one_symbol = '[<](bold purple)'
vimcmd_replace_symbol = '[<](bold purple)'
vimcmd_visual_symbol = '[<](bold yellow)'
disabled = false
